/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as GuiaRouteImport } from './routes/guia'
import { Route as CancelRouteImport } from './routes/cancel'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiPublicCreemWebhookRouteImport } from './routes/api/public/creem-webhook'

const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaRoute = GuiaRouteImport.update({
  id: '/guia',
  path: '/guia',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelRoute = CancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreemWebhookRoute = ApiPublicCreemWebhookRouteImport.update({
  id: '/api/public/creem-webhook',
  path: '/api/public/creem-webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/guia': typeof GuiaRoute
  '/success': typeof SuccessRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/public/creem-webhook': typeof ApiPublicCreemWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/guia': typeof GuiaRoute
  '/success': typeof SuccessRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/public/creem-webhook': typeof ApiPublicCreemWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancel': typeof CancelRoute
  '/guia': typeof GuiaRoute
  '/success': typeof SuccessRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/public/creem-webhook': typeof ApiPublicCreemWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cancel'
    | '/guia'
    | '/success'
    | '/api/checkout'
    | '/api/public/creem-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cancel'
    | '/guia'
    | '/success'
    | '/api/checkout'
    | '/api/public/creem-webhook'
  id:
    | '__root__'
    | '/'
    | '/cancel'
    | '/guia'
    | '/success'
    | '/api/checkout'
    | '/api/public/creem-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancelRoute: typeof CancelRoute
  GuiaRoute: typeof GuiaRoute
  SuccessRoute: typeof SuccessRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiPublicCreemWebhookRoute: typeof ApiPublicCreemWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia': {
      id: '/guia'
      path: '/guia'
      fullPath: '/guia'
      preLoaderRoute: typeof GuiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancel': {
      id: '/cancel'
      path: '/cancel'
      fullPath: '/cancel'
      preLoaderRoute: typeof CancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/creem-webhook': {
      id: '/api/public/creem-webhook'
      path: '/api/public/creem-webhook'
      fullPath: '/api/public/creem-webhook'
      preLoaderRoute: typeof ApiPublicCreemWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancelRoute: CancelRoute,
  GuiaRoute: GuiaRoute,
  SuccessRoute: SuccessRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiPublicCreemWebhookRoute: ApiPublicCreemWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
